# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
        
    - name: Restore node_modules cache
      id: restore-node_modules
      uses: actions/cache/restore@v3
      with:
        path: |
          **/node_modules
          some/other/dependencies
        key: npm-${{ hashFiles("**/package.json", "**/package-lock.json") }}
        
#     - run:
    - name: Install npm dependencies
      run: "[ ! -d node_modules ] && npm ci || echo Using cached node_modules."

    - name: Save node_modules cache
      id: cache-node_modules
      uses: actions/cache/save@v3
      with:
        path: |
          **/node_modules
        key: npm-${{ hashFiles("**/package.json", "**/package-lock.json") }}
        
    - name: Snapshots and Unit Tests
      run: npm run test
    - name: Component and E2E Tests
      run: npm run test:ct
